replicas: 2
name: springboot-app

image:
  repositorynames: 210613553230.dkr.ecr.us-east-2.amazonaws.com/springboot-app-githubactions   # change this to the one with your account id and repo name
  tag: latest

container:
  name: springboot-app
service:
  name: springboot-app-service
  type: NodePort
  port: 8080
 # targetPort: 9000

