apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sprintboot-app
  name: "{{ .Values.name }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: sprintboot-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sprintboot-app
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" # khajaehtesham/sprintboot-app:latest
          name: "{{ .Values.container.name }}"

