
name: 'Scan the code, Build and deploy the java containerized application'

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'manifests/**'
      - 'README.md'
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:

  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-1
          role-to-assume: arn:aws-cn:iam::210613553230:role/github-id-role
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
